#Diccionario con la clave de cifrado para cada elemento o caracter

cifrado = { 'x': "a",
			'ó': "b",
			's': "c",
			'q': "d",
			'j': "e",
			'ú': "f",
			'o': "g",
			'm': "h",
			'k': "i",
			'g': "j",
			'i': "k",
			'c': "l",
			'á': "m",
			'u': "n",
			'e': "ñ",
			'd': "o",
			'h': "p",
			'é': "q",
			'l': "r",
			'n': "s",
			'p': "t",
			'r': "u",
			'y': "v",
			'í': "w",
			'ñ': "x",
			'z': "y",
			'ü': "z",
			'w': "á",	#Vocales con asento y dieresis
			'a': "é",
			'b': "í",
			'f': "ó",
			't': "ú",
			'v': "ü"
			#'Ã': "f",
			#'º': "u"
}